// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.20.3
// source: protos/compatibility.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Registration statuses
type Response_ResultType int32

const (
	Response_UNSPECIFIED Response_ResultType = 0
	Response_SUCCESS     Response_ResultType = 1
	Response_ERROR       Response_ResultType = 2
	Response_DENIED      Response_ResultType = 3
)

// Enum value maps for Response_ResultType.
var (
	Response_ResultType_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "SUCCESS",
		2: "ERROR",
		3: "DENIED",
	}
	Response_ResultType_value = map[string]int32{
		"UNSPECIFIED": 0,
		"SUCCESS":     1,
		"ERROR":       2,
		"DENIED":      3,
	}
)

func (x Response_ResultType) Enum() *Response_ResultType {
	p := new(Response_ResultType)
	*p = x
	return p
}

func (x Response_ResultType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Response_ResultType) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_compatibility_proto_enumTypes[0].Descriptor()
}

func (Response_ResultType) Type() protoreflect.EnumType {
	return &file_protos_compatibility_proto_enumTypes[0]
}

func (x Response_ResultType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Response_ResultType.Descriptor instead.
func (Response_ResultType) EnumDescriptor() ([]byte, []int) {
	return file_protos_compatibility_proto_rawDescGZIP(), []int{1, 0}
}

// A CompatRequest compares a requesting application compatibility metadata with a host node
// The request can provide the entire artifact as a payload, or a URI to retrieve
// from a registry
type CompatRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Payload string `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	Uri     string `protobuf:"bytes,2,opt,name=uri,proto3" json:"uri,omitempty"`
}

func (x *CompatRequest) Reset() {
	*x = CompatRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_compatibility_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CompatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompatRequest) ProtoMessage() {}

func (x *CompatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_compatibility_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompatRequest.ProtoReflect.Descriptor instead.
func (*CompatRequest) Descriptor() ([]byte, []int) {
	return file_protos_compatibility_proto_rawDescGZIP(), []int{0}
}

func (x *CompatRequest) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *CompatRequest) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Payload    string              `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	Compatible bool                `protobuf:"varint,2,opt,name=compatible,proto3" json:"compatible,omitempty"`
	Status     Response_ResultType `protobuf:"varint,3,opt,name=status,proto3,enum=convergedcomputing.org.grpc.v1.Response_ResultType" json:"status,omitempty"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_compatibility_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_protos_compatibility_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_protos_compatibility_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *Response) GetCompatible() bool {
	if x != nil {
		return x.Compatible
	}
	return false
}

func (x *Response) GetStatus() Response_ResultType {
	if x != nil {
		return x.Status
	}
	return Response_UNSPECIFIED
}

var File_protos_compatibility_proto protoreflect.FileDescriptor

var file_protos_compatibility_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x74, 0x69,
	0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1e, 0x63, 0x6f,
	0x6e, 0x76, 0x65, 0x72, 0x67, 0x65, 0x64, 0x63, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x69, 0x6e, 0x67,
	0x2e, 0x6f, 0x72, 0x67, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x76, 0x31, 0x22, 0x3b, 0x0a, 0x0d,
	0x43, 0x6f, 0x6d, 0x70, 0x61, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a,
	0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x69, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x69, 0x22, 0xd4, 0x01, 0x0a, 0x08, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64,
	0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x74, 0x69, 0x62, 0x6c, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x74, 0x69, 0x62, 0x6c, 0x65,
	0x12, 0x4b, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x33, 0x2e, 0x63, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x67, 0x65, 0x64, 0x63, 0x6f, 0x6d, 0x70,
	0x75, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x6f, 0x72, 0x67, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x76,
	0x31, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x41, 0x0a,
	0x0a, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0f, 0x0a, 0x0b, 0x55,
	0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07,
	0x53, 0x55, 0x43, 0x43, 0x45, 0x53, 0x53, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x45, 0x52, 0x52,
	0x4f, 0x52, 0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06, 0x44, 0x45, 0x4e, 0x49, 0x45, 0x44, 0x10, 0x03,
	0x32, 0x85, 0x01, 0x0a, 0x14, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x74, 0x69, 0x62, 0x69, 0x6c, 0x69,
	0x74, 0x79, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x6d, 0x0a, 0x12, 0x43, 0x68, 0x65,
	0x63, 0x6b, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x74, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x12,
	0x2d, 0x2e, 0x63, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x67, 0x65, 0x64, 0x63, 0x6f, 0x6d, 0x70, 0x75,
	0x74, 0x69, 0x6e, 0x67, 0x2e, 0x6f, 0x72, 0x67, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x76, 0x31,
	0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x28,
	0x2e, 0x63, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x67, 0x65, 0x64, 0x63, 0x6f, 0x6d, 0x70, 0x75, 0x74,
	0x69, 0x6e, 0x67, 0x2e, 0x6f, 0x72, 0x67, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x76, 0x31, 0x2e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x27, 0x5a, 0x25, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x6f, 0x6d, 0x70, 0x73, 0x70, 0x65, 0x63, 0x2f,
	0x63, 0x6f, 0x6d, 0x70, 0x61, 0x74, 0x2d, 0x6c, 0x69, 0x62, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_compatibility_proto_rawDescOnce sync.Once
	file_protos_compatibility_proto_rawDescData = file_protos_compatibility_proto_rawDesc
)

func file_protos_compatibility_proto_rawDescGZIP() []byte {
	file_protos_compatibility_proto_rawDescOnce.Do(func() {
		file_protos_compatibility_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_compatibility_proto_rawDescData)
	})
	return file_protos_compatibility_proto_rawDescData
}

var file_protos_compatibility_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protos_compatibility_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protos_compatibility_proto_goTypes = []interface{}{
	(Response_ResultType)(0), // 0: convergedcomputing.org.grpc.v1.Response.ResultType
	(*CompatRequest)(nil),    // 1: convergedcomputing.org.grpc.v1.CompatRequest
	(*Response)(nil),         // 2: convergedcomputing.org.grpc.v1.Response
}
var file_protos_compatibility_proto_depIdxs = []int32{
	0, // 0: convergedcomputing.org.grpc.v1.Response.status:type_name -> convergedcomputing.org.grpc.v1.Response.ResultType
	1, // 1: convergedcomputing.org.grpc.v1.CompatibilityService.CheckCompatibility:input_type -> convergedcomputing.org.grpc.v1.CompatRequest
	2, // 2: convergedcomputing.org.grpc.v1.CompatibilityService.CheckCompatibility:output_type -> convergedcomputing.org.grpc.v1.Response
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protos_compatibility_proto_init() }
func file_protos_compatibility_proto_init() {
	if File_protos_compatibility_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_compatibility_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CompatRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_compatibility_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_compatibility_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_compatibility_proto_goTypes,
		DependencyIndexes: file_protos_compatibility_proto_depIdxs,
		EnumInfos:         file_protos_compatibility_proto_enumTypes,
		MessageInfos:      file_protos_compatibility_proto_msgTypes,
	}.Build()
	File_protos_compatibility_proto = out.File
	file_protos_compatibility_proto_rawDesc = nil
	file_protos_compatibility_proto_goTypes = nil
	file_protos_compatibility_proto_depIdxs = nil
}
